<a href="https://colab.research.google.com/github/PAM-cake/DA-ML_practice./blob/main/Basic_Matrices_OperN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

ADDITION

In [2]:
#Matrix Addition
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = a+b
print(c)

[[ 8 10 12]
 [14 16 18]]


In [5]:
#with random value
matrix_1 = np.random.randint(1,10, size=(4,4))
matrix_2 = np.random.randint(1,10, size=(4,4))
sum = matrix_1 + matrix_2
print(sum)

[[ 9 15  8  2]
 [17 10 11 14]
 [ 6  8 13  8]
 [ 9 11  2  7]]


In [6]:
#without creating variable using inbuilt function.
np.add(matrix_1, matrix_2)

array([[ 9, 15,  8,  2],
       [17, 10, 11, 14],
       [ 6,  8, 13,  8],
       [ 9, 11,  2,  7]])

SUBTRACTION

In [7]:
#Matrix Subraction
matrix_1 = np.random.randint(1,10, size=(4,4))
matrix_2 = np.random.randint(1,10, size=(4,4))
sub = matrix_1 - matrix_2
print(sub)

[[ 7 -1 -3  0]
 [ 2  0  0 -2]
 [ 1 -3  3  0]
 [ 1  0  2  3]]


In [8]:
np.subtract(matrix_1, matrix_2)

array([[ 7, -1, -3,  0],
       [ 2,  0,  0, -2],
       [ 1, -3,  3,  0],
       [ 1,  0,  2,  3]])

MULTIPLICATION

In [9]:
#Multiplication of Vectors
x = 5
y = np.random.randint(1,10,size=(4,4))
print(y)

[[5 8 7 7]
 [9 4 9 7]
 [2 3 3 5]
 [5 3 7 8]]


In [10]:
product = x*y
print(product)

[[25 40 35 35]
 [45 20 45 35]
 [10 15 15 25]
 [25 15 35 40]]


In [11]:
np.multiply(x,y)

array([[25, 40, 35, 35],
       [45, 20, 45, 35],
       [10, 15, 15, 25],
       [25, 15, 35, 40]])

In [12]:
#Multplying Two Matrices
matrix_1 = np.random.randint(1,10, size=(4,4))
matrix_2 = np.random.randint(1,10, size=(4,4))
print(matrix_1)
print(matrix_2)

[[8 8 9 7]
 [5 3 2 7]
 [3 1 9 6]
 [3 7 8 2]]
[[5 8 5 4]
 [8 4 8 1]
 [6 7 2 8]
 [5 3 5 3]]


In [13]:
mult = np.dot(matrix_1, matrix_2)
print(mult)

[[193 180 157 133]
 [ 96  87  88  60]
 [107 109  71 103]
 [129 114  97  89]]


In [14]:
mult.shape

(4, 4)

In [15]:
np.matmul(matrix_1, matrix_2)

array([[193, 180, 157, 133],
       [ 96,  87,  88,  60],
       [107, 109,  71, 103],
       [129, 114,  97,  89]])